## **Lab Exercise #3**
- Name: Michael Kenny
- Date Started: 9/10/2025
- Date Completed: 9/10/2025
- Class: CSC-180-02
- Professor: Dr. Mamoun Abu-Samaha

**Assignment Objective:**
- Recreate the model as shown in the lecture slides for the csv file (homePricesMedian.csv).

**Test Cases/Predictions:**
- Test1 -> area = 3000, bedrooms = 3, age = 40
- Test2 -> area = 2500, bedrooms = 4, age = 5

### **1. Reading CSV File into Dataframe**

In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv('./homePricesMedian.csv')
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Notice that some values in the dataframe are not available, for whatever the reason. Values must be numerical throughout the entire column in order for the model to accept the input. We have to substitute something in somehow.

### **2. Filling NaN Entries (Data pre-processing)**

In [5]:
df.bedrooms.median()

3.5

The most logical substitutions for missing values seem to be either the median value of the remaining existing ones or the mean value. This is a developer decision and we should pick whichever one matches the data most closely.

In [6]:
import math
median_bedrooms = math.floor(df.bedrooms.median()) # Take the floor, only integers allowed. can't have half a bedroom.
median_bedrooms

3

In [7]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [8]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

### **3. Training/Fitting Model**

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

Creates the model based off the inputs: area, bedrooms, age, and outputs: price.

In [10]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [11]:
reg.intercept_

383724.99999999977

### **4. Test Cases (Predictions)**

#### **Test Case 1**

In [12]:
reg.predict([[3000, 3, 40]])

c:\Users\Micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([444400.])

In [13]:
137.25*3000+-26025*3+-6825*40+383724.9999999983

444399.9999999983

Above is a confirmation using the proposed equation of the model and the matching coefficients.

#### **Test Case 2**

In [14]:
reg.predict([[2500, 4, 5]])

c:\Users\Micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([588625.])

In [15]:
137.25*2500+-26025*4+-6825*5+383724.9999999983

588624.9999999984

### **5. Conclusion**

###

Overall this exercise was slightly more involved than the previous two. Upon receiving the data, when analyzing it it is easy to notice that the data has values missing in some columns. This requires us to pre-process some of the data before the model processes it. This is because the model cannot handle values that are non-numerical, so missing/NaN values are an issue.