## **Lab Exercise #5**
- Name: Michael Kenny
- Date Started: 9/11/2025
- Date Completed: 9/12/2025
- Class: CSC-180-02
- Professor: Dr. Mamoun Abu-Samaha

**Assignment Objective:**
- Recreate the model as shown in the lecture slides for the csv file (test_scores.csv).

**Test Cases/Predictions:**
- Candidate1 -> math score = 60
- Candidate2 -> math score = 90
- Candidate3 -> math score = 20

### **1. Reading CSV File into Dataframe**

In [9]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [10]:
df = pd.read_csv('./test_scores.csv')
df.head()

     name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83

### **2. Create Input/Output Variables**

In [11]:
X = df.drop(['name', 'cs'], axis='columns')
X

   math
0    92
1    56
2    88
3    70
4    80
5    49
6    65
7    35
8    66
9    67

Dropping the name and cs columns make sense to me as the only input we will require is the math score column. The cs column will become the output column, while the name column is composed of unique nominal values.

Does that mean dropping this column is correct? Since we are predicting values in the form of:
    model.predict([[math_score]]) -> predicted_cs_score
Only the math score is required to predict the correlated cs score, so the name of the student is nominal and is irrelevant to the model? (I am unsure if this is a correct/valid approach).

In [12]:
y = df.cs
y

0    98
1    68
2    81
3    80
4    83
5    52
6    66
7    30
8    68
9    73
Name: cs, dtype: int64

### **3. Training/Fitting Model**

In [13]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

### **4. Test Cases (Predictions)**

#### **Test Case 1**

In [14]:
model.predict([[60]])

c:\Users\Micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([62.97939358])

#### **Test Case 2**

In [15]:
model.predict([[90]])

c:\Users\Micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([93.51148072])

#### **Test Case 3**

In [16]:
model.predict([[20]])

c:\Users\Micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([22.26994407])

### **5. Conclusion**

This exercise was very straight forward if I am assuming that the name column is in fact uniquely nominal and able to be dropped from the dataframe before training the model. If I am correct in this assumption, then this model is extremely simple and only takes in a single input column in order to output.